config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'games/index'

  get 'copies/index'

  get 'public', to: 'games#index'
  resources :copies

  root to: "games#index"

end

app/models/copy.rb
class Copy < ActiveRecord::Base
belongs_to :user
belongs_to :game
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :copies
  has_many :users, through: :copies
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :games, through: :copies
  has_many :copies       


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController

def index
  
end  

def create
  current_user.copies.create(copy_params)
  redirect_to copies_path
end  

def new
  @copy = Copy.new
end

def edit
  @copy = Copy.find(params[:id])
end  

def update
  copy = current_user.copies.find(params[:id])
  copy.update(copy_params)
  redirect_to copies_path
end  

def destroy
  copy = current_user.copies.find(params[:id])
  copy.destroy
  redirect_to copies_path
end  

private
def copy_params
  params.require(:copy).permit(:game_id, :rating)
end  

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

def index
  @games = Game.all.sort
end  

def new
  
end

def edit

end 

def create

end  

def update

end  

def show
end

def destroy

end  



private





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/copy_helper.rb
module CopyHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/copies/edit.html.erb
<p> Choose Game To Edit</p>   
<%= form_for @copy do |f| %>
  <%= f.collection_select(:game_id, Game.all, :id,:name) %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  
  <%= f.submit 'Edit'%>
<%end%>   

app/views/copies/index.html.erb
<ul>
  
<%current_user.copies.each do |c|%>
<li><%= c.game.name %> | <%= c.rating%>
| <%= link_to('Edit', edit_copy_path(c)) %>
 <%= button_to('Delete', copy_path(c), method: :delete, data: {confirm: "Are you sure?"})%>
<br>

</li>

<%end%>
</ul>

<%= link_to 'Add a copy', new_copy_path %>

app/views/copies/new.html.erb
<h1> Add a copy </h1>

<p> Choose Game </p>   
<%= form_for @copy do |f| %>
  <%= f.collection_select(:game_id, Game.all, :id,:name) %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  
  <%= f.submit 'Add'%>
<%end%>   

app/views/games/index.html.erb
<%@games.each do |game|%>
<%= game.name %>
<br>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<div class='login'>
  <% if current_user %> 
  <%= current_user.email %>
  <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
<%else%>
     <%= link_to 'Sign In', new_user_session_path %>
     <%= link_to 'Register', new_user_registration_path %>
<%end%>


</div>




<nav>

<ul>
  
<li><%=link_to 'Home', root_path %> </li>     
<li><%=link_to 'My Games', copies_path %> </li>
</ul>
</nav>
<%= yield %>

</body>
</html>